### ISSUE TITLE
App can not switch to Article page

### ISSUE THREAD

**Issue by titanjer** [reapp/hacker-news-app#1]
I clone this example and npm install, reapp run!

First problem is wrong path require in "reapp-router/react-router/RoutedViewListMixin.js ."
https://github.com/reapp/reapp-routes/commit/536437a08d46f5d9bbe9a113009420494077d6f6
Therefore, I revert to new style manually and app shows the article list page! (Y)

Second problem is not able to switch article page when I click the detail icon. Console error is 
Uncaught TypeError: Cannot read property 'dispatch' of undefined in "react-router/modules/createRouter.js:317 ."

btw, it seems that react-router does not support react 0.13 very well. If I create a app by "reapp new app", the button on Left Navigation in example app has click errors, too.

**Comment by natew** [comment]
Can you try again? We've updated a few things.

**Comment by titanjer** [comment]
no~ problem still exists! @@
- first is the wrong require path for the react-router, **react-router/modules/** or **react-router/mixins/** ?!
  ![reapp-routes](https://cloud.githubusercontent.com/assets/389191/6254624/24acb712-b7e5-11e4-933d-b925fec72da0.png)
- second is the tap error on Articles, I can not transition to article page!
  ![screen shot 2015-02-19 at 3 09 53](https://cloud.githubusercontent.com/assets/389191/6254638/41755a5c-b7e5-11e4-9936-fccda5da9ea5.png)

**Comment by natew** [comment]
Hmm... the react-rotuer path should be right because we've specified a github react-router. Could you check that your npm_modules/react-router is the same as `https://github.com/reapp/react-router#0cb83ddd3c`, and then also make sure your reapp-routes version is 0.9.9 (run `npm outdated` and be sure to update all those).

If that doesn't work, could you output `npm list` and put it here? Sorry for the troubles!

**Comment by titanjer** [comment]
**RouteHandlerMixin.js** put in **modules/** at above version (https://github.com/reapp/react-router#0cb83ddd3c).
Howevere, in the [**reapp-routes/react-router/RoutedViewListMixin.js**](https://github.com/reapp/reapp-routes/blob/master/react-router/RoutedViewListMixin.js#L2), the require path is **react-router/mixins/RouteHandler**.
Why does not it be the **react-router/modules/RouteHandlerMixin**?!

Excuse me for interrupt u! @@

**Comment by natew** [comment]
You were right! I changed to the right version and pushed.

**Comment by titanjer** [comment]
Awesome!!
