### ISSUE TITLE
http://localhost:3011/main.js   not found

### ISSUE THREAD

**Issue by jay3dec** [reapp/hacker-news-app#11]
After cloning the sample app when I try to run `reapp run` it says 

```
Your app is running on http://localhost:3010
```

But when I try to browse the above URL it's blank with an error in console

```
GET http://localhost:3011/main.js  not found
```

**Comment by natew** [comment]
Could you output the result of `reapp run -d`?

**Comment by jay3dec** [comment]
It seems like I hadn't run `npm install`. Now it's all good. Thanks :)
