### ISSUE TITLE
App fails to run ?

### ISSUE THREAD

**Issue by dowsanjack** [reapp/hacker-news-app#14]
When I try to build and run this, I get this

this._processChildContext is not a function

[HMR] Waiting for update signal from WDS...
webpack:///./~/reapp-kit/~/reapp-ui/lib/contextPatch.js?:84 

Uncaught TypeError: this._processChildContext is not a function
webpack:///(webpack)-dev-server/client?:15 

[WDS] Hot Module Replacement enabled.
webpack:///(webpack)-dev-server/client?:36 

[WDS] Warnings while compiling.
webpack:///(webpack)-dev-server/client?:38 ./app/app.js

Critical dependencies:
11:22-29 require function is used in a way in which dependencies cannot be statically extracted
 @ ./app/app.js 11:22-29

**Comment by boopathi** [comment]
:+1: Getting the same error! 

Also, What is the `npm start` for in `package.json` ?

**Comment by boopathi** [comment]
It worked for react `0.13.2` and not `0.13.3` ..
