### ISSUE TITLE
Not able to run this app

### ISSUE THREAD

**Issue by neerajsingh0101** [reapp/hacker-news-app#8]
Error log is here https://gist.github.com/neerajdotname/b0b78b35fb0ed20a63e7 .

**Comment by natew** [comment]
Sorry I commented on your gist and not here. I pushed up a fix for this, let me know if it works.

**Comment by neerajsingh0101** [comment]
Now I'm getting different error.

https://gist.github.com/neerajdotname/5df5850d3dd4e7479d04

**Comment by natew** [comment]
That looks like bluebird wasn't included. Wonder if it would be working now?

**Comment by natew** [comment]
Should be fixed, closing unless you still experience.
